Architecture globale de yacine clicker
Karnak19/Yacine-Cliker pull request #15
Opened 2019-04-09 14:12 UTC by Muxwcs

**json update:**
react-retro-hit-counter added
**index.html update:**
light cleaning
**App.css deleted**
**App.js update:**
import counter
**init_app.css created:**
stylesheet for yacine clicker architecture
**img directory created** 
bg image in

2019-04-09 14:13 UTC, Muxwcs commented
Siouplait?

2019-04-10 08:12 UTC, Karnak19 commented on src/App.js
> +// HOMEMADE COMPONENTS
Du code mort ici

2019-04-10 08:12 UTC, Karnak19 commented on src/App.js
> +              {/* <img
Pareil ici, du code mort :)

2019-04-10 08:13 UTC, Karnak19 commented on src/init_app.css
> +    /* background-color: lightslategrey; */
Code mort

2019-04-10 08:13 UTC, Karnak19 requested changes
C'est pas mal dans l'ensemble, attention tout de même au code mort !

2019-04-10 14:27 UTC, closed without merging